# Generated by Django 4.2.2 on 2023-06-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
